site_name: KAD

nav:
  - Home: index.md
  - "Getting started / Tutorials":
    - "Preparation": getting-started/preparation.md
    - "Installation on an existing Cluster": getting-started/installation-existing-cluster.md
    - "Deploying applications": getting-started/deploying-applications.md
    - "Application stack": getting-started/application-stack.md
  - "User guide":
    - "Concepts and entities": guide/concepts-overview.md
    - "Component": guide/component.md
    - "ComponentRelease": guide/component-release.md
    - "Template": guide/template.md
    - "TemplateRelease": guide/template-release.md
    - "Dependencies": guide/dependencies.md
    - "Schemas": guide/schemas.md
    - "Usage": guide/usage.md
#    - "Document":
#    - "loaders / multi-repositories": guide/loaders.md
#    - "GitRepository":
#    - "AirGap":
#    - "Delete and protection":
  - "Extensions":
    - "KAD CLI": extensions/kadcli.md
    - "Rest API": extensions/rest-api.md
    - "User GUI": extensions/user-gui.md

#  - "References":
#    - "Components": reference/components.md
#    - "ComponentRelease": reference/component-releases.md

theme:
#  name: readthedocs
#  titles_only: false
#  name: mkdocs
#  name: windmill-dark
#  name: gitbook
  #  name: dracula
  name: material
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
#    - content.code.copy
#    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

repo_url: https://github.com/kubotal/kad-controller
