site_name: KAD

nav:
  - Home: index.md
  - "Getting started / Tutorials":
    - "Preparation": getting-started/01-preparation.md
    - "Using an existing Cluster": getting-started/05-installation-existing-cluster.md
    - "Installation on kind": getting-started/10-kind.md
    - "A first deployment": getting-started/15-a-first-deployment.md
    - "The deployment process": getting-started/20-the-deployment-process.md
    - "improving component": getting-started/25-improving-component.md
    - "Debugging": getting-started/30-debugging.md
    - "The context": getting-started/35-context.md
    - "The KAD CLI": getting-started/40-kadcli.md
    - "Application stack": getting-started/45-stack.md
    - "Dependencies": getting-started/50-dependencies.md
  - "User guide":
    - "Concepts and entities": guide/10-concepts-overview.md
    - "Schemas": guide/15-schemas.md
    - "KAD CLI": guide/25-kadcli.md
    - "Git access": guide/30-git-access.md
    - "Document": guide/35-document.md
    - "loaders / multi-repositories": guide/40-loaders.md
    - "GitRepository": guide/45-git-repository.md
    - "Air Gap": guide/50-air-gap.md
    - "Deletion and protection": guide/55-deletion.md
    - "kad-controller configuration": guide/60-configuration.md
  - "References":
    - "Components": reference/10-components.md
    - "ComponentRelease": reference/15-component-release.md
    - "Template": reference/20-template.md
    - "TemplateRelease": reference/25-template-release.md

theme:
#  name: readthedocs
#  titles_only: false
#  name: mkdocs
#  name: windmill-dark
#  name: gitbook
  #  name: dracula
  name: material
  palette:
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer
#    - content.code.copy
#    - content.code.select

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details

repo_url: https://github.com/kubotal/kad-controller
